module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  autologout: 0
  automated_cron: 0
  better_exposed_filters: 0
  better_normalizers: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  civicrm: 0
  civicrmtheme: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_browser_enhanced: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_browser: 0
  filter: 0
  flippy: 0
  fontawesome: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  inline_entity_form: 0
  link: 0
  mailchimp: 0
  mailchimp_signup: 0
  media: 0
  menu_ui: 0
  mt_cookieconsent: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  search: 0
  serialization: 0
  settings_tray: 0
  shortcut: 0
  superfish: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  video_embed_field: 0
  views_infinite_scroll: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  slint2020: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
