flippy_page: 0
flippy_head_page: 0
flippy_show_empty_page: 0
flippy_prev_label_page: ''
flippy_next_label_page: ''
flippy_first_last_page: 0
flippy_first_label_page: ''
flippy_last_label_page: ''
flippy_loop_page: 0
flippy_random_page: 0
flippy_random_label_page: ''
flippy_truncate_page: ''
flippy_ellipse_page: ''
flippy_press_swipe_page: null
flippy_custom_sorting_page: 0
flippy_sort_page: nid
flippy_order_page: ASC
flippy_mt_album: 0
flippy_head_mt_album: 0
flippy_show_empty_mt_album: 0
flippy_prev_label_mt_album: ''
flippy_next_label_mt_album: ''
flippy_first_last_mt_album: 0
flippy_first_label_mt_album: ''
flippy_last_label_mt_album: ''
flippy_loop_mt_album: 0
flippy_random_mt_album: 0
flippy_random_label_mt_album: ''
flippy_truncate_mt_album: ''
flippy_ellipse_mt_album: ''
flippy_press_swipe_mt_album: null
flippy_custom_sorting_mt_album: 0
flippy_sort_mt_album: nid
flippy_order_mt_album: ASC
flippy_mt_post: 0
flippy_head_mt_post: 0
flippy_show_empty_mt_post: 0
flippy_prev_label_mt_post: ''
flippy_next_label_mt_post: ''
flippy_first_last_mt_post: 0
flippy_first_label_mt_post: ''
flippy_last_label_mt_post: ''
flippy_loop_mt_post: 0
flippy_random_mt_post: 0
flippy_random_label_mt_post: ''
flippy_truncate_mt_post: ''
flippy_ellipse_mt_post: ''
flippy_press_swipe_mt_post: null
flippy_custom_sorting_mt_post: 0
flippy_sort_mt_post: nid
flippy_order_mt_post: ASC
