flippy_page: 0
flippy_head_page: 0
flippy_show_empty_page: 0
flippy_prev_label_page: ''
flippy_next_label_page: ''
flippy_first_last_page: 0
flippy_first_label_page: ''
flippy_last_label_page: ''
flippy_loop_page: 0
flippy_random_page: 0
flippy_random_label_page: ''
flippy_truncate_page: ''
flippy_ellipse_page: ''
flippy_press_swipe_page: null
flippy_custom_sorting_page: 0
flippy_sort_page: nid
flippy_order_page: ASC
