lazy.settings:
  type: config_object
  mapping:
    image_fields:
      type: sequence
      label: 'Image fields'
      sequence:
        type: string
        label: 'Image field'
    alter_tag:
      type: mapping
      label: 'Inline elements to be lazy-loaded via filter'
      mapping:
        img:
          type: string
          label: 'Enable for images'
        iframe:
          type: string
          label: 'Enable for iframes'
    formatters:
      type: mapping
      label: 'Additional image formatters'
      mapping:
        lazy_image:
          type: string
          label: 'Image (Lazy-load)'
        lazy_responsive_image:
          type: string
          label: 'Responsive image (Lazy-load)'
    skipClass:
      type: string
      label: skipClass
    disabled_paths:
      type: string
      label: disabled_paths
    placeholderSrc:
      type: string
      label: placeholderSrc
    preferNative:
      type: boolean
      label: preferNative
    lazysizes:
      type: mapping
      mapping:
        lazyClass:
          type: string
          label: lazyClass
        loadedClass:
          type: string
          label: loadedClass
        loadingClass:
          type: string
          label: loadingClass
        preloadClass:
          type: string
          label: preloadClass
        errorClass:
          type: string
          label: errorClass
        autosizesClass:
          type: string
          label: autosizesClass
        srcAttr:
          type: string
          label: srcAttr
        srcsetAttr:
          type: string
          label: srcsetAttr
        sizesAttr:
          type: string
          label: sizesAttr
        minSize:
          type: integer
          label: minSize
        customMedia:
          type: sequence
          label: customMedia
          sequence:
            type: string
            label: 'Custom Media'
        init:
          type: boolean
          label: init
        expFactor:
          type: float
          label: expFactor
        hFac:
          type: float
          label: hFac
        loadMode:
          type: integer
          label: loadMode
        loadHidden:
          type: boolean
          label: loadHidden
        ricTimeout:
          type: integer
          label: ricTimeout
        throttleDelay:
          type: integer
          label: throttleDelay
        plugins:
          type: sequence
          label: plugins
          sequence:
            type: string
            label: Plugin

field.formatter.third_party.lazy:
  type: mapping
  label: 'Per field lazy-loading setting'
  mapping:
    lazy_image:
      type: string
      label: 'Lazy-loading'
